=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/progetto.dtd
<!ELEMENT TEI (teiHeader, facsimile?, text)>
<!ATTLIST TEI xmlns CDATA #FIXED "http://www.tei-c.org/ns/1.0">

<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title, respStmt)>

<!ELEMENT title (#PCDATA | hi | term | foreign | quote | orgName | persName | lb | pb)*>

<!ELEMENT respStmt (resp, name)>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT publicationStmt (p)>
<!ELEMENT sourceDesc (bibl)>

<!ELEMENT p (#PCDATA | lb | pb | persName | placeName | geogName | orgName | date | term | foreign | title | quote | hi | bibl | note | pubPlace)*>
<!ATTLIST p facs CDATA #IMPLIED>

<!ELEMENT bibl (#PCDATA | title | biblScope | date | pubPlace | publisher | author | orgName | hi | persName | lb)*>
<!ELEMENT biblScope (#PCDATA)>
<!ATTLIST biblScope unit CDATA #IMPLIED>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date when CDATA #IMPLIED>
<!ELEMENT pubPlace (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT author (#PCDATA | forename | surname)*>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

<!ELEMENT facsimile (surface+)>
<!ELEMENT surface (graphic, zone*)>
<!ATTLIST surface xml:id ID #REQUIRED>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic url CDATA #REQUIRED width CDATA #IMPLIED height CDATA #IMPLIED>
<!ELEMENT zone EMPTY>
<!ATTLIST zone xml:id ID #IMPLIED ulx CDATA #IMPLIED uly CDATA #IMPLIED lrx CDATA #IMPLIED lry CDATA #IMPLIED>

<!ELEMENT text (body)>
<!ELEMENT body (div)>

<!ELEMENT div (pb | head | opener | p | closer | note)*>
<!ATTLIST div type CDATA #IMPLIED>

<!ELEMENT head (#PCDATA | persName | placeName | bibl | term | hi | title | lb | pb)*>
<!ATTLIST head facs CDATA #IMPLIED>

<!ELEMENT opener (salute)>
<!ELEMENT salute (#PCDATA | lb | persName)*>
<!ELEMENT closer (signed)>
<!ELEMENT signed (#PCDATA | hi | persName | lb)*>
<!ATTLIST signed facs CDATA #IMPLIED>

<!ELEMENT note (#PCDATA | hi | title | placeName | persName | orgName | date)*>
<!ATTLIST note n CDATA #IMPLIED place CDATA #IMPLIED>

<!ELEMENT lb EMPTY>
<!ATTLIST lb facs CDATA #IMPLIED break CDATA #IMPLIED>

<!ELEMENT pb EMPTY>
<!ATTLIST pb n CDATA #IMPLIED facs CDATA #IMPLIED>

<!ELEMENT persName (#PCDATA | hi | lb)*>
<!ELEMENT placeName (#PCDATA | lb)*>
<!ELEMENT geogName (#PCDATA | lb)*>
<!ELEMENT orgName (#PCDATA | hi | lb)*>
<!ELEMENT term (#PCDATA | hi | foreign | lb)*>
<!ATTLIST term type CDATA #IMPLIED>
<!ELEMENT foreign (#PCDATA | hi | lb)*>
<!ATTLIST foreign xml:lang CDATA #IMPLIED>

<!ELEMENT quote (#PCDATA | lb | pb | persName | placeName | geogName | orgName | date | term | foreign | title | hi)*>

<!ELEMENT hi (#PCDATA | persName | placeName | date | term | foreign | title | lb | pb | orgName)*>
<!ATTLIST hi rend CDATA #IMPLIED>

=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/articolo3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE TEI SYSTEM "progetto.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Il Congresso Igienico di Milano</title>
                <respStmt>
                    <resp>Progetto di codifica di testi</resp>
                    <name>Beggiato Camilla e Franchi Gemma</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Edizione digitale didattica</p>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>La Rassegna Settimanale</title>
                    <biblScope unit="volume">8</biblScope>
                    <biblScope unit="issue">204</biblScope>
                    <date when="1881-11-27">27 Novembre 1881</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </teiHeader>

    <facsimile>
        <surface xml:id="pag350">
            <graphic url="Articolo 3.jpg" width="739.4px" height="1063.4px" />
            <zone xml:id="a3_p1_titolo" ulx="406" uly="756" lrx="664" lry="776" />
            <zone xml:id="a3_p1" ulx="379" uly="776" lrx="699" lry="829" />
            <zone xml:id="a3_p2" ulx="375" uly="832" lrx="699" lry="868" />
        </surface>

        <surface xml:id="pag351">
            <graphic url="Articolo 3 pag2.jpg" width="738.4px" height="1058.4px" />
            <zone xml:id="a3_p3" ulx="34" uly="43" lrx="358" lry="138" />
            <zone xml:id="a3_p4" ulx="35" uly="140" lrx="359" lry="203" />
            <zone xml:id="a3_p5" ulx="35" uly="207" lrx="359" lry="296" />
            <zone xml:id="a3_firma" ulx="282" uly="300" lrx="343" lry="312" />
        </surface>
    </facsimile>

    <text>
        <body>
            <div type="articolo">
                
                <pb n="350" facs="#pag350"/>
                
                <head facs="#a3_p1_titolo">IL CONGRESSO IGIENICO DI <placeName>MILANO</placeName>.</head>
                
                <opener>
                    <salute>Al Direttore.</salute>
                </opener>

                <p facs="#a3_p1">
                    <lb/>L'articolo della <orgName>Rassegna</orgName> (<bibl>vol. VIII, pag. 274</bibl>) sul <hi rend="italic"><term>Con-
                    <lb/>gresso Igienico</term></hi> tenutosi nel <date when="1881-09">settembre</date> a <placeName>Milano</placeName>, pecca di
                    <lb/>non poche inesattezze.
                </p>

                <p facs="#a3_p2">
                    <lb/>Non è giusta l'asserzione che al <orgName>Congresso</orgName> sia stata
                    <lb/>impossibile <quote>« ogni larva di studio o d'esame. »</quote> Infatti i temi
                    <lb/>erano stati annunciati assai tempo prima affinchè ciascuno
                    <lb/>avesse tempo a prepararcisi. Le discussioni animatissime
                    <lb/>che vi si agitarono, mostrarono che non sempre le parole del
                    <lb/>relatore erano accolte ciecamente e tumultuosamente, come
                    <lb/>lascia supporre l'articolista. Mi basti l'accennare, ad esempio,
                    <lb/>la votazione dell'assemblea sulle proposte del relatore pro-
                    <lb/>fessore <persName>Pagliani</persName> rispetto al miglior sistema di <term>fognatura</term>
                    <lb/>delle città.
                </p>

                <pb n="351" facs="#pag351"/>

                <p facs="#a3_p3">
                    <lb/>Nel giudizio che la <orgName>Rassegna</orgName> porta sulla relazione del
                    <lb/>prof. <persName>Sormani</persName> al tema: <title><hi rend="italic">Profilassi delle malattie veneree</hi></title>, si
                    <lb/>parla di <quote>« statistiche parziali, per diversi rispetti eccepibili, di
                    <lb/>affastellamento irrazionale di cifre. »</quote> Ora il <persName>Sormani</persName> stette ri-
                    <lb/>gorosamente alle risultanze di sole cifre ufficiali.
                </p>

                <p facs="#a3_p4">
                    <lb/>Nè sussiste l'accusa che sulle conclusioni del sig. <persName>Sor-
                    <lb/>mani</persName> si sia votato <quote>« senza discussione, »</quote> chè anzi l'ordine del
                    <lb/>giorno del prof. <persName>De Giovanni</persName> che sanzionò quelle conclusioni
                    <lb/>superò un vivissimo dibattito. Nè si può dire mancante
                    <lb/>di serietà tale votazione, perchè col sig. <persName>Sormani</persName> stette la
                    <lb/>gran maggioranza dei medici.
                </p>

                <p facs="#a3_p5">
                    <lb/>Finalmente la <orgName>Rassegna</orgName> accusa il <persName>Sormani</persName> d'aver pro-
                    <lb/>posto brutalmente l'estensione della <term>visita sanitaria</term> alle donne
                    <lb/>addette a stabilimenti industriali. Ora nè egli, nè nessun
                    <lb/>altro ha mai pensato di comprare a prezzo della <term>pubblica
                    <lb/>moralità</term> il più lieve vantaggio sociale. Egli accennò invece
                    <lb/>all'opportunità di estendere la visita sanitaria, oltre che ai
                    <lb/>soldati di terra e di mare, agli <term>operai celibi</term> delle grandi in-
                    <lb/>dustrie; e tra quest'ultima proposta e la prima ognun vede
                    <lb/>l'immensa differenza.
                </p>

                <closer>
                    <signed facs="#a3_firma"><hi rend="italic">Dev.mo</hi> T.</signed>
                </closer>
            </div>
        </body>
    </text>
</TEI>

=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/notizie2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE TEI SYSTEM "progetto.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Notizie - Vol 8</title>
                <respStmt>
                    <resp>Progetto di codifica di testi</resp>
                    <name>Beggiato Camilla e Franchi Gemma</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Edizione digitale didattica</p>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>La Rassegna Settimanale</title>
                    <biblScope unit="volume">8</biblScope>
                    <biblScope unit="issue">204</biblScope>
                    <date when="1881-11-27">27 Novembre 1881</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </teiHeader>

    <facsimile>
        <surface xml:id="pag352">
            <graphic url="Notizie 2.jpg" width="738.4px" height="1061.4px"/>
            
            <zone xml:id="notizie_titolo" ulx="527" uly="504" lrx="593" lry="520"/>
            
            <zone xml:id="notizie_n1" ulx="399" uly="523" lrx="720" lry="572"/>
            
            <zone xml:id="notizie_n2" ulx="399" uly="577" lrx="722" lry="596"/>
            
            <zone xml:id="notizie_n3" ulx="397" uly="599" lrx="725" lry="892"/>
        </surface>
    </facsimile>

    <text>
        <body>
            <div type="notizie">
                <head facs="#notizie_titolo">NOTIZIE.</head>
                
                <p facs="#notizie_n1">
                    <lb/>— La Commissione, incaricata di pubblicare le lettere e gli scritti
                    <lb/>di <persName>Pietro il Grande</persName>, comincerà, potendo, quest'anno la stampa del suo
                    <lb/>lavoro. Chiunque possieda manoscritti di <persName>Pietro il Grande</persName> o scritti da
                    <lb/>lui firmati è pregato di mandarli alla Commissione, che fattili copiare,
                    <lb/>glie li renderà o gli darà un esemplare della pubblicazione.
                </p>

                <p facs="#notizie_n2">
                    <lb/>— È annunziata per la fine di quest'anno la pubblicazione della
                    <lb/>traduzione dell'<title><hi rend="italic">Ecclesiaste</hi></title>, di <persName>Ernesto Renan</persName>
                    con una estesa prefazione.
                </p>

                <p facs="#notizie_n3">
                    <lb/>— In una biblioteca privata in <placeName>Inghilterra</placeName> si è trovato un mano-
                    <lb/>scritto contenente un poema francese fino ad oggi completamente sco-
                    <lb/>nosciuto, il cui argomento è la storia particolareggiata di <persName>Guglielmo
                    <lb/>il Maresciallo</persName>, conte di <placeName>Pembroke</placeName>, che fu reggente d'<placeName>Inghilterra</placeName> nei
                    <lb/>primi anni della minorità di <persName>Enrico III</persName>. Questo poema, che non con-
                    <lb/>tiene meno di 19212 versi ottosillabici dev'essere stato composto negli
                    <lb/>anni che seguirono la morte di <persName>Guglielmo il Maresciallo</persName>, cioè poco dopo
                    <lb/>il 1219. L'autore non si nomina, ma fa conoscere chi gli fornì gli ele-
                    <lb/>menti (che dovevano essere molto numerosi e molto esatti) del suo la-
                    <lb/>voro; era un certo <persName>Giovanni Erlea</persName>, che figura frequentemente nei do-
                    <lb/>cumenti diplomatici del tempo di <persName>Giovanni senza terra</persName> e di <persName>Enrico III</persName>
                    <lb/>sotto il nome di <foreign xml:lang="la"><hi rend="italic">Johannes de Erlegia</hi></foreign>. Era stato scudiero di <persName>Guglielmo
                    <lb/>il Maresciallo</persName> e più tardi uno dei suoi cavalieri. Il poema abbonda di
                    <lb/>ragguagli assolutamente nuovi e di una incontestabile autenticità su
                    <lb/>una infinità di punti della storia della <placeName>Francia</placeName> e dell'<placeName>Inghilterra</placeName> dal
                    <lb/>1140 circa fino al 1219. Vi sono preziosi particolari su <persName>Enrico au court
                    <lb/>Mantel</persName>, un racconto curiosissimo della salita al trono di <persName>Riccardo Cuor
                    <lb/>di Leone</persName>, molti fatti nuovi intorno alle guerre di <persName>Riccardo</persName> e di <persName>Fi-
                    <lb/>lippo Augusto</persName>, i torbidi in <placeName>Irlanda</placeName>, sotto il re <persName>Giovanni</persName>, l'invasione di
                    <lb/><persName>Luigi</persName>, figlio di <persName>Filippo Augusto</persName>, in <placeName>Inghilterra</placeName>, ecc. L'opera è già in-
                    <lb/>teramente copiata e si stamperà presto; intanto una notizia abbastanza
                    <lb/>estesa sarà pubblicata in uno dei prossimi numeri della <title><hi rend="italic">Romania</hi></title>.
                </p>
            </div>
        </body>
    </text>
</TEI>
