=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/progetto.dtd
<!ELEMENT TEI (teiHeader, facsimile?, text)>
<!ATTLIST TEI xmlns CDATA #FIXED "http://www.tei-c.org/ns/1.0">

<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title, respStmt)>

<!ELEMENT title (#PCDATA | hi | term | foreign | quote | orgName | persName | lb | pb)*>

<!ELEMENT respStmt (resp, name)>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT publicationStmt (p)>
<!ELEMENT sourceDesc (bibl)>

<!ELEMENT p (#PCDATA | lb | pb | persName | placeName | geogName | orgName | date | term | foreign | title | quote | hi | bibl | note | pubPlace)*>
<!ATTLIST p facs CDATA #IMPLIED>

<!ELEMENT bibl (#PCDATA | title | biblScope | date | pubPlace | publisher | author | orgName | hi | persName | lb)*>
<!ELEMENT biblScope (#PCDATA)>
<!ATTLIST biblScope unit CDATA #IMPLIED>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date when CDATA #IMPLIED>
<!ELEMENT pubPlace (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT author (#PCDATA | forename | surname)*>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

<!ELEMENT facsimile (surface+)>
<!ELEMENT surface (graphic, zone*)>
<!ATTLIST surface xml:id ID #REQUIRED>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic url CDATA #REQUIRED width CDATA #IMPLIED height CDATA #IMPLIED>
<!ELEMENT zone EMPTY>
<!ATTLIST zone xml:id ID #IMPLIED ulx CDATA #IMPLIED uly CDATA #IMPLIED lrx CDATA #IMPLIED lry CDATA #IMPLIED>

<!ELEMENT text (body)>
<!ELEMENT body (div)>

<!ELEMENT div (pb | head | opener | p | closer | note)*>
<!ATTLIST div type CDATA #IMPLIED>

<!ELEMENT head (#PCDATA | persName | placeName | bibl | term | hi | title | lb | pb)*>
<!ATTLIST head facs CDATA #IMPLIED>

<!ELEMENT opener (salute)>
<!ELEMENT salute (#PCDATA | lb | persName)*>
<!ELEMENT closer (signed)>
<!ELEMENT signed (#PCDATA | hi | persName | lb)*>
<!ATTLIST signed facs CDATA #IMPLIED>

<!ELEMENT note (#PCDATA | hi | title | placeName | persName | orgName | date)*>
<!ATTLIST note n CDATA #IMPLIED place CDATA #IMPLIED>

<!ELEMENT lb EMPTY>
<!ATTLIST lb facs CDATA #IMPLIED break CDATA #IMPLIED>

<!ELEMENT pb EMPTY>
<!ATTLIST pb n CDATA #IMPLIED facs CDATA #IMPLIED>

<!ELEMENT persName (#PCDATA | hi | lb)*>
<!ELEMENT placeName (#PCDATA | lb)*>
<!ELEMENT geogName (#PCDATA | lb)*>
<!ELEMENT orgName (#PCDATA | hi | lb)*>
<!ELEMENT term (#PCDATA | hi | foreign | lb)*>
<!ATTLIST term type CDATA #IMPLIED>
<!ELEMENT foreign (#PCDATA | hi | lb)*>
<!ATTLIST foreign xml:lang CDATA #IMPLIED>

<!ELEMENT quote (#PCDATA | lb | pb | persName | placeName | geogName | orgName | date | term | foreign | title | hi)*>

<!ELEMENT hi (#PCDATA | persName | placeName | date | term | foreign | title | lb | pb | orgName)*>
<!ATTLIST hi rend CDATA #IMPLIED>

=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/articolo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE TEI SYSTEM "progetto.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Ammonizione e Domicilio Coatto</title>
                <respStmt>
                    <resp>Progetto di codifica di testi</resp>
                    <name>Beggiato Camilla e Franchi Gemma</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Edizione digitale didattica</p>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>La Rassegna Settimanale</title>
                    <biblScope unit="volume">1</biblScope>
                    <biblScope unit="issue">8</biblScope>
                    <date when="1878-02-24">24 Febbraio 1878</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </teiHeader>

    <facsimile>
        <surface xml:id="pag125">
            <graphic url="articolo 1.jpg" width="739px" height="1063px" />
            <zone xml:id="a1_titolo" ulx="50" uly="50" lrx="600" lry="100" />
            <zone xml:id="a1_p1" ulx="50" uly="110" lrx="600" lry="300" />
            <zone xml:id="a1_p2" ulx="50" uly="310" lrx="600" lry="500" />
        </surface>

        <surface xml:id="pag126">
            <graphic url="articolo 1 pag2.jpg" width="739px" height="1063px" />
            <zone xml:id="a1_p3" ulx="50" uly="50" lrx="600" lry="200" />
            <zone xml:id="a1_p4" ulx="50" uly="210" lrx="600" lry="400" />
            <zone xml:id="a1_p5" ulx="50" uly="410" lrx="600" lry="600" />
            <zone xml:id="a1_p6" ulx="50" uly="610" lrx="600" lry="800" />
        </surface>
    </facsimile>

    <text>
        <body>
            <div type="articolo">
                
                <pb n="125" facs="#pag125"/>
                
                <head facs="#a1_titolo">AMMONIZIONE E <term>DOMICILIO COATTO</term>.</head>

                <p facs="#a1_p1">
                    <lb/>Siamo noi un popolo libero? Chi sfogli i nostri Codici
                    <lb/>non ne può dubitare. Ad ogni pagina si manifesta un ri-
                    <lb/>spetto religioso della <term>libertà personale</term> di ciascun cittadino,
                    <lb/>libertà che è fondamento e fine di tutte le altre. [...]
                </p>

                <p facs="#a1_p2">
                    <lb/>o anche statario. Per il <title>Codice penale italiano</title> (art. 47)
                    <lb/>anche l'<term>ammonizione</term> s'infligge per un fatto. [...]
                </p>

                <pb n="126" facs="#pag126"/>

                <p facs="#a1_p3">
                    <lb/>V' ha un istituto inteso più specialmente d'ogni altro
                    <lb/>ad impedire che il <orgName>potere esecutivo</orgName> adoperi l'organismo giu-
                    <lb/>diziario come istrumento di prepotenza [...]
                    <lb/>già capito che intendiamo il <term>giurì</term>. [...]
                </p>

                <p facs="#a1_p4">
                    <lb/>...Il semplice cittadino è in balìa all'<term>ammonizione</term>, non quella
                    <lb/>del <title>Codice penale</title>, ma quella della legge di <term>pubblica sicu-
                    <lb/>rezza</term> del <date>1875</date>, provvedimento di polizia inflitto da un ma-
                    <lb/>gistrato amovibile; l'<term>ammonito</term>, violati i precetti indeter-
                    <lb/>minatissimi impostigli, può essere mandato dal Ministro
                    <lb/>dell'Interno, cioè dalla polizia, a <term>domicilio coatto</term> anche per
                    <lb/>cinque anni.
                </p>

                <p facs="#a1_p5">
                    <lb/>morale del nostro personale giudiziario e di pubblica sicu-
                    <lb/>rezza, nelle lungaggini inefficaci della nostra procedura
                    <lb/>penale. E pure, deputati e ministri d'ogni partito, fanno
                    <lb/>a gara nel peggiorare ancora quel personale...
                </p>

                <p facs="#a1_p6">
                    <lb/>...Diciamo di essere una nazione giovane:
                    <lb/>siamo piuttosto un popolo bimbo. Come quei bambini cui
                    <lb/>la mamma ha portato dalla fiera l'orologio di foglia d'ot-
                    <lb/>tone vanno attorno dicendo: <quote>« <hi rend="italic">Vedete, l'ho anch'io l'oro-
                    <lb/>logio che si carica,</hi> »</quote> così noi andiamo pavoneggiandoci per
                    <lb/>l'<placeName>Europa</placeName> colla nostra libertà; <term>libertà</term> da tre soldi che non
                    <lb/>cammina e che, invece di dar vita a tutte le forze della
                    <lb/>nazione per farle cooperare al suo benessere e al suo vi-
                    <lb/>gore, ci accascia con tutte le debolezze proprie delle oli-
                    <lb/>garchie decrepite, e ci toglie di sperare perfino quell'ener-
                    <lb/>gia che il <term>dispotismo</term> seppe talvolta infondere nei popoli.
                </p>
            </div>
        </body>
    </text>
</TEI>

=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/Articolo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE TEI SYSTEM "progetto.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Emigrazione e Colonizzazione</title>
                <respStmt>
                    <resp>Progetto di codifica di testi</resp>
                    <name>Beggiato Camilla e Franchi Gemma</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Edizione digitale didattica</p>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>La Rassegna Settimanale</title>
                    <biblScope unit="volume">5</biblScope>
                    <biblScope unit="issue">120</biblScope>
                    <date when="1880-04-18">18 Aprile 1880</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </teiHeader>

    <facsimile>
        <surface xml:id="pag272">
            <graphic url="Articolo 2.jpg" width="727.4px" height="1051.4px" />
            <zone xml:id="a2_titolo" ulx="50" uly="50" lrx="600" lry="80" />
            <zone xml:id="a2_p1" ulx="50" uly="90" lrx="600" lry="300" />
            <zone xml:id="a2_p2" ulx="50" uly="310" lrx="600" lry="500" />
            <zone xml:id="a2_p3" ulx="50" uly="510" lrx="600" lry="900" />
        </surface>

        <surface xml:id="pag273">
            <graphic url="Articolo 2 pag2.jpg" width="709.4px" height="1066.4px" />
            <zone xml:id="a2_p4" ulx="50" uly="50" lrx="600" lry="300" />
            <zone xml:id="a2_firma" ulx="400" uly="310" lrx="600" lry="350" />
        </surface>
    </facsimile>

    <text>
        <body>
            <div type="articolo">
                <pb n="272" facs="#pag272"/>
                
                <head facs="#a2_titolo">EMIGRAZIONE E <term>COLONIZZAZIONE</term>.</head>

                <p facs="#a2_p1">
                    <lb/>Ogni volta che accade di parlare dell'<term type="theme">emigrazione</term>, il pen-
                    <lb/>siero corre a quegli <term>agenti arruolatori</term> le cui bugiarde se-
                    <lb/>duzioni sono state tanto fatali a migliaia e migliaia delle
                    <lb/>nostre migliori braccia. Di tutti i provvedimenti che il <orgName>governo</orgName>
                    <lb/>può prendere in faccia al doloroso esodo il solo su
                    <lb/>cui non cada discussione è la necessità d'invigilare efficace-
                    <lb/>mente la loro condotta; e a questo principalmente miravano
                    <lb/>i due progetti di legge <persName>Del Giudice</persName> e <persName>Minghetti</persName>-<persName>Luzzatti</persName>,
                    <lb/>da tanto tempo presentati al nostro <orgName>Parlamento</orgName>, che pote-
                    <lb/>rono già intanto essere conciliati in uno solo. [...]
                </p>

                <p facs="#a2_p2">
                    <lb/>Gli Stati dell'<placeName>America</placeName> sono ben lungi dall'avere messo
                    <lb/>a coltura tutto il loro suolo. [...]
                    <lb/>Qua i terreni vennero posti partitamente a immediato con-
                    <lb/>tatto dell'<term>emigrante</term> che arrivava con poco o nessun <term>capi-
                    <lb/>tale</term> perchè appunto si voleva costituire una classe demo-
                    <lb/>cratica di piccoli <term>proprietari</term> agiati ed indipendenti, là invece
                    <lb/>diventarono una specie di <term>beneficio feudale</term> di pochi privi-
                    <lb/>legiati. [...]
                </p>
                
                <p facs="#a2_p3">
                    <lb/>Così s'accrebbe il numero dei <term>latifondi</term>. Quei proprietari
                    <lb/>che intrapresero la conduzione diretta, abbagliati dagli
                    <lb/>enormi profitti della <term>coltura estensiva</term>, abituati quasi gene-
                    <lb/>ralmente a vederla riescire mercè l'impiego degli <term>schiavi</term>,
                    <lb/>non poterono così presto lasciarsi persuadere dalla dottrina
                    <lb/>della compartecipazione delle braccia ai frutti della terra,
                    <lb/>e seguitarono ancora a mantenersi in diretto antagonismo
                    <lb/>cogl'interessi e le speranze del <term>lavoro</term>. Come dapprima
                    <lb/>alimentarono la <term>tratta dei negri</term>, come si valsero poi del-
                    <lb/>l'importazione dei <foreign xml:lang="en">coolies</foreign>, ora ricorrono alla seduzione degli
                    <lb/>elementi più poveri della popolazione agricola europea; chè
                </p>

                <pb n="273" facs="#pag273"/>
                
                <p facs="#a2_p4">
                    <lb/>se ad essi promettono qualche ettaro, o in dono o a prezzi
                    <lb/>minimi, circondano la promessa di tali condizioni da rendere
                    <lb/>facile il proclamarli decaduti quando appunto i lavori di dis-
                    <lb/>sodamento o di miglioria son più progrediti, e intanto colle
                    <lb/>anticipazioni e coi sussidi hanno posto loro indosso peggiori
                    <lb/>catene di quelle della <term>schiavitù</term>.
                </p>

                <closer>
                    <signed facs="#a2_firma">X</signed>
                </closer>
            </div>
        </body>
    </text>
</TEI>

=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/bibliografia1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE TEI SYSTEM "progetto.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Bibliografia: Giovanni De Castro</title>
                <respStmt>
                    <resp>Progetto di codifica di testi</resp>
                    <name>Beggiato Camilla e Franchi Gemma</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Edizione digitale didattica</p>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>La Rassegna Settimanale</title>
                    <biblScope unit="volume">1</biblScope>
                    <biblScope unit="issue">8</biblScope>
                    <date when="1878-02-24">24 Febbraio 1878</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </teiHeader>

    <facsimile>
        <surface xml:id="pag142">
            <graphic url="Bibliografia 1.jpg" width="733px" height="1073px"/>
            <zone xml:id="bib_titolo" ulx="52" uly="880" lrx="378" lry="891"/>
            <zone xml:id="bib_pubblicazione" ulx="74" uly="895" lrx="168" lry="904"/>
            <zone xml:id="bib_p1" ulx="55" uly="928" lrx="378" lry="996"/>
            <zone xml:id="bib_p2" ulx="384" uly="77" lrx="708" lry="165"/>
            <zone xml:id="bib_p3" ulx="385" uly="172" lrx="707" lry="360"/>
            <zone xml:id="bib_p4" ulx="387" uly="367" lrx="707" lry="416"/>
        </surface>
    </facsimile>

    <text>
        <body>
            <div type="bibliografia">
                <head facs="#bib_titolo">
                    <bibl>
                        <author>
                            <forename>GIOVANNI</forename>
                            <surname>DE CASTRO</surname>
                        </author>.
                        <title>I popoli dell'antico Oriente, volumi due.</title>
                    </bibl>
                </head>

                <p facs="#bib_pubblicazione">
                    — <pubPlace>Milano</pubPlace>, <date>1878</date>.
                </p>

                <p facs="#bib_p1">
                    <lb/>In quest'opera l'Autore s'è proposto di darci <quote>« un rac-
                    <lb/>conto del tutto familiare delle vicende »</quote> de' popoli orientali
                    <lb/>trattando delle <quote>« società e stati che fiorirono nell'<placeName>Asia</placeName> ante-
                    <lb/>riore, colà ove gli Italiani, fin d'antico, ebbero dominio e poi
                    <lb/>quella dimestichezza, migliore della conquista, che il com-
                    <lb/>mercio agevola e raffina »</quote> (p. x): ossia, in altri termini, trat-
                </p>

                <p facs="#bib_p2">
                    <lb/>tando di tutte quelle schiatte e nazioni, la cui storia forma
                    <lb/>argomento d'ogni altro libro di simil genere. Le civiltà che
                    <lb/>nacquero e si svolsero per tutto il territorio compreso fra
                    <lb/>l'<placeName>Indo</placeName> e il <placeName>Mar Nero</placeName>, sulle coste asiatiche del <placeName>Mediterraneo</placeName>,
                    <lb/>e nella valle del <placeName>Nilo</placeName>, passano rapidamente dinanzi agli
                    <lb/>occhi del lettore, in quadri non di rado ben disegnati.
                </p>

                <p facs="#bib_p3">
                    <lb/>Se il signor <persName>De Castro</persName> ha avuto in animo di fare un
                    <lb/>libro di amena e piacevole lettura, egli c'è riuscito in
                    <lb/>molta parte. E in tal caso non gli s'avrebbe che a rim-
                    <lb/>proverare qualche difettuccio di forma, un criterio non
                    <lb/>sempre uniforme nel coordinare i fatti e nella scelta dei
                    <lb/>medesimi, e il promettere, alcuna volta, ne' titoli de' capi-
                    <lb/>toli più di quel che spesso vi si trova. Così, per esempio,
                    <lb/>in un luogo il lettore s'aspetta d'aver notizie sulla lette-
                    <lb/>ratura egiziana; e poi vien solo a sapere, che nel <placeName>Rama-
                    <lb/>seum</placeName> a <placeName>Karnak</placeName> nove piccole stanze dovevano contener
                    <lb/>papiri, perchè sulla porta d'ingresso sta l'immagine di
                    <lb/><persName>Thot</persName>, Dio della letteratura: il quale del resto si trova ef-
                    <lb/>figiato anche su altre porte che non mettono sempre a bi-
                    <lb/>blioteche. In altro luogo si promette di dire alcuna cosa
                    <lb/>de' primi ricordi storici degli Arii, e poi non si trovano
                    <lb/>che poche parole intorno allo <hi rend="italic"><title>Sciah-nameh</title></hi>. Ma se, oltre a
                    <lb/>un libro d'amena lettura, l'Autore avesse anche inteso di
                    <lb/>fare un lavoro che dovesse servir davvero all'incremento
                    <lb/>degli studi, per quel che concerne la storia orientale, egli
                    <lb/>non ha pienamente conseguito lo scopo. Inquantochè, a
                    <lb/>parer nostro, manca in queste pagine quello che uno stu-
                    <lb/>dioso di buona volontà cerca, e ha diritto di trovare, anche
                    <lb/>in un libro elementare di questo genere: cioè a dire un
                    <lb/>aiuto che lo metta sulla strada di procurarsi più solide e
                    <lb/>amplie notizie della materia a cui egli attende. Mai una
                    <lb/>citazione viene a confortare le asserzioni dell'Autore; mai
                    <lb/>uno di que' nomi legati alle più belle e recenti conquiste
                    <lb/>dell'<term>Archeologia orientale</term>, si porge alla memoria di chi legge.
                </p>

                <p facs="#bib_p4">
                    <lb/>Se il signor <persName>De Castro</persName>, in altra edizione, riuscisse a ri-
                    <lb/>mediare a ciò, potrebbe rendere molto più utile il suo libro,
                    <lb/>senza che ne scapitasse il diletto, che viene dalla forma fa-
                    <lb/>miliare e viva con cui egli s'è adoperato ad esporre i fatti.
                </p>
            </div>
        </body>
    </text>
</TEI>

=== camillabeggiato3/Progetto-CdT-Beggiato-Franchi/notizie1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE TEI SYSTEM "progetto.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Notizie</title>
                <respStmt>
                    <resp>Progetto di codifica di testi</resp>
                    <name>Beggiato Camilla e Franchi Gemma</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Edizione digitale didattica</p>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>La Rassegna Settimanale</title>
                    <biblScope unit="volume">1</biblScope>
                    <biblScope unit="issue">8</biblScope>
                    <date when="1878-02-24">24 Febbraio 1878</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </teiHeader>

    <facsimile>
        <surface xml:id="pag144">
            <graphic url="Notizie 1.jpg" width="727px" height="1063px" />
            <zone xml:id="not_titolo" ulx="175" uly="750" lrx="239" lry="761" />
            <zone xml:id="not_monaci" ulx="43" uly="767" lrx="366" lry="801" />
            <zone xml:id="not_trollope" ulx="44" uly="807" lrx="366" lry="825" />
            <zone xml:id="not_manzoni" ulx="44" uly="829" lrx="366" lry="888" />
            <zone xml:id="not_amari" ulx="43" uly="894" lrx="366" lry="975" />
            <zone xml:id="not_thiers" ulx="382" uly="68" lrx="704" lry="91" />
            <zone xml:id="not_bitard" ulx="380" uly="96" lrx="702" lry="157" />
            <zone xml:id="not_bigot" ulx="381" uly="161" lrx="702" lry="261" />
            <zone xml:id="not_hellwald" ulx="381" uly="264" lrx="702" lry="311" />
            <zone xml:id="not_westminster" ulx="380" uly="315" lrx="702" lry="410" />
            <zone xml:id="not_besant" ulx="380" uly="415" lrx="700" lry="484" />
            <zone xml:id="not_samter" ulx="378" uly="489" lrx="700" lry="539" />
            <zone xml:id="not_bamberger" ulx="377" uly="543" lrx="700" lry="575" />
            <zone xml:id="not_social" ulx="378" uly="580" lrx="700" lry="612" />
            <zone xml:id="not_wilson" ulx="379" uly="617" lrx="700" lry="676" />
            <zone xml:id="not_archeo" ulx="377" uly="681" lrx="700" lry="928" />
        </surface>
    </facsimile>

    <text>
        <body>
            <div type="notizie">
                <head facs="#not_titolo">NOTIZIE.</head>
                
                <p facs="#not_monaci">
                    <lb/>— <persName>Ernesto Monaci</persName>, professore di lingue romanze all'Università di
                    <lb/><placeName>Roma</placeName>, ha scoperto un manoscritto importante, relativo alla storia di
                    <lb/><persName>Federigo Barbarossa</persName>. È un poema di quasi 3000 versi latini.
                </p>
                
                <p facs="#not_trollope">
                    <lb/>— La <title>Vita di Pio IX</title> di <persName>Tommaso Adolfo Trollope</persName> (2 vol. <orgName>Bentley</orgName>)
                    <lb/>recentemente pubblicata in inglese, non incontra il favor della critica.
                </p>
                
                <p facs="#not_manzoni">
                    <lb/>— Nell'annunziare la pubblicazione del poema, finora sconosciuto,
                    <lb/>del <persName>Manzoni</persName> <title>Del Trionfo della libertà</title>, il <orgName><hi rend="italic">Magazin für die Literatur des
                    <lb/>Auslandes</hi></orgName> (<date>16 febbraio</date>) fa notare l'importanza di questo lavoro.
                </p>
                
                <p facs="#not_amari">
                    <lb/>— Il professor <persName>Amari</persName> si applica indefessamente alla traduzione ita-
                    <lb/>liana, con note ec., della <title>Biblioteca arabo-sicula</title> ossia <title>Raccolta di testi
                    <lb/>arabici che toccano la Geografia, la Storia, le Biografie e la Bibliografia</title>
                    <lb/><hi rend="italic">della <placeName>Sicilia</placeName></hi>.
                </p>
                
                <p facs="#not_thiers">
                    <lb/>— Si annunzia la prossima pubblicazione delle orazioni del <persName>Thiers</persName>
                    <lb/>pronunziate da lui come presidente della Repubblica (1871-73).
                </p>
                
                <p facs="#not_bitard">
                    <lb/>— Il <persName>Bitard</persName> ha pubblicato (da <orgName>Dreyfus</orgName> a <placeName>Parigi</placeName>) un <title>Dizionario ge-
                    <lb/>nerale della biografia contemporanea</title> che l'<orgName><hi rend="italic">Athenaeum</hi></orgName> giudica
                    <lb/>superiore a quello del <persName>Vapereau</persName>.
                </p>
                
                <p facs="#not_bigot">
                    <lb/>— Nella <orgName><hi rend="italic">Revue politique et littéraire</hi></orgName> (<date>16 febbraio</date>) <persName>Charles Bigot</persName> di-
                    <lb/>scorre del pontificato di <persName>Pio IX</persName>.
                </p>
                
                <p facs="#not_hellwald">
                    <lb/>— Nell' <orgName><hi rend="italic">Ausland</hi></orgName>, n. 1-6, <persName>Fr. Hellwald</persName> ha pubblicato degli studi
                    <lb/>sulla quistione d'Oriente considerandola come quistione di civiltà.
                </p>
                
                <p facs="#not_westminster">
                    <lb/>— Nella <orgName><hi rend="italic">Westminster Review</hi></orgName> del <date when="1878-01">Gennaio 1878</date>, si esaminano le pub-
                    <lb/>blicazioni di statistica fatto per cura del cessato Ministero di Agricoltura.
                </p>
                
                <p facs="#not_besant">
                    <lb/>— Nell'articolo <title>Il movimento Maltusiano in Inghilterra</title>, pubblicato
                    <lb/>nel n. 7 della <orgName><hi rend="italic">Rassegna</hi></orgName>, annunziammo che la signora <persName>Besant</persName> e l'editore
                    <lb/><persName>Bradlaugh</persName> si erano appellati contro la sentenza.
                </p>
                
                <p facs="#not_samter">
                    <lb/>— Nella <orgName><hi rend="italic">Gegenwart</hi></orgName> (n. 6), <persName>Walter Rogge</persName> fa un resoconto molto fa-
                    <lb/>vorevole del libro di <persName>Adolfo Samter</persName>, <title>Sulla proprietà collettiva</title>.
                </p>
                
                <p facs="#not_bamberger">
                    <lb/>— Nella <orgName><hi rend="italic">Rundschau</hi></orgName> del <date>febbraio</date> il <persName>Bamberger</persName> ci fa il quadro del
                    <lb/>socialismo in <placeName>Germania</placeName>.
                </p>
                
                <p facs="#not_social">
                    <lb/>— Si annunzia la prossima pubblicazione a <placeName>Londra</placeName> di una nuova
                    <lb/>Rivista settimanale, <title>Social Notes</title>, diretta da <persName>S. C. Hall</persName>.
                </p>
                
                <p facs="#not_wilson">
                    <lb/>— Nell' <orgName><hi rend="italic">Academy</hi></orgName> (<date>9 febbraio</date>), <persName>Charles Heath Wilson</persName> fa la descri-
                    <lb/>zione di un sepolcro antico a <placeName>San Germano</placeName>.
                </p>
                
                <p facs="#not_archeo">
                    <lb/>— Quasi tutti i giornali di <placeName>Europa</placeName> hanno ripetuto in questi ultimi
                    <lb/>tempi la falsa notizia di meravigliose scoperte di antichità fatte presso
                    <lb/>l'antica <placeName>Siponto</placeName>, non lungi da <placeName>Manfredonia</placeName>.
                </p>
            </div>
        </body>
    </text>
</TEI>
